/*
 * Copyright 2026 Salar Rahmanian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import cats.effect.{IO, Resource}
import laika.api.*
import laika.api.bundle.{
  BlockDirectives,
  DirectiveRegistry,
  LinkDirectives,
  SpanDirectives,
  TemplateDirectives
}
import laika.ast.*
import laika.ast.Path.Root
import laika.format.*
import laika.helium.Helium
import laika.helium.config.*
import laika.io.api.TreeTransformer
import laika.io.syntax.*
import laika.theme.config.Color

import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale
import scala.util.Try

/** The site's Helium theme and Markdown transformer, shared by `LaikaBuild`
  * and `LaikaPreview`.
  *
  * Colours: Helium's teal, with scala-lang.org's red (deepened a little, to
  * `c42b28`, so small text keeps AA contrast on the sidebar's pale background)
  * and its dark navy top bar (set in `docs/css/scalanews.css`). Dark mode keeps
  * Helium's own palette.
  */
object SiteTheme {

  private val helium = Helium.defaults
    .all.metadata(
      title = Some("Scala News"),
      description = Some(SiteFiles.siteDescription),
      language = Some("en")
    )
    .all.themeColors(
      primary = Color.hex("007c99"),
      primaryMedium = Color.hex("a7d4de"),
      primaryLight = Color.hex("eef5f6"),
      secondary = Color.hex("c42b28"),
      text = Color.hex("5f5f5f"),
      background = Color.hex("ffffff"),
      bgGradient = (Color.hex("002b36"), Color.hex("007c99"))
    )
    .site.topNavigationBar(
      homeLink = TextLink.internal(Root / "index.md", "Scala News"),
      navLinks = Seq(
        TextLink.internal(Root / "Resources" / "Blog_Directory.md", "Bloggers"),
        TextLink.external("https://www.scala-lang.org/community", "Community"),
        // The Atom feed of editions (generated by SiteFiles).
        TextLink.internal(Root / "feed.xml", "RSS"),
        IconLink.external(
          "https://github.com/softinio/scalanews",
          HeliumIcon.github
        )
      ),
      highContrast = true
    )
    .site.favIcons(
      Favicon.internal(Root / "img" / "favicon-32x32.png", sizes = "32x32")
    )
    .site.mainNavigation(depth = 3)
    // Newsletter pages are short and flat; the sidebar is enough.
    .site.pageNavigation(enabled = false)
    .site.internalCSS(Root / "css" / "scalanews.css")
    // GoatCounter analytics; the script loads count.js itself (see the file).
    .site.internalJS(Root / "js" / "goatcounter.js")
    .site.footer(
      TemplateString(
        """<br/>
          |Created by <a href="https://www.softinio.com">Salar Rahmanian</a> and Contributors.
          || """.stripMargin
      ),
      SpanLink.internal(Root / "Resources" / "CODE_OF_CONDUCT.md")(
        "Code of Conduct"
      ),
      TemplateString(
        """
          |<br/>
          |<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />The content on this site by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Salar Rahmanian and contributors</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<br/>
          |Made with ❤️ in San Francisco using: | <a href="https://typelevel.org/cats-effect/">cats-effect</a> | <a href="https://typelevel.org/Laika/">Laika</a> |
          |""".stripMargin
      )
    )
    .build

  private val editionPrefix = "Scala News - "

  // The date in an edition's heading, as FileHandler writes it.
  private val headingDateFormat =
    DateTimeFormatter.ofPattern("MMMM d, uuuu", Locale.ENGLISH)

  /** The ISO date ("2024-11-24") for a heading date ("November 24, 2024"). */
  private def isoDate(headingDate: String): Option[String] =
    Try(LocalDate.parse(headingDate.trim, headingDateFormat)).toOption
      .map(_.toString)

  /** Renders an edition's "# Scala News - March 3, 2023" heading as a small
    * "Scala News" label above the date: the top bar already names the site.
    * The heading's text is unchanged, so the page's `<title>` keeps the full
    * name.
    */
  private val editionTitle: RewriteRule[Block] = {
    case header @ Header(1, Seq(Text(text, textOptions)), _)
        if text.startsWith(editionPrefix) =>
      RewriteAction.Replace(
        header.withContent(
          Seq(
            Text(editionPrefix.stripSuffix(" - "), Styles("edition-brand")),
            Text(" - ", Styles("edition-separator")),
            // Rendered as <time> (see `transformer`) when it parses as a date.
            Text(
              text.stripPrefix(editionPrefix),
              textOptions + Styles("edition-date")
            )
          )
        )
      )
  }

  /** `@:scalanewsPageMeta`, used in `docs/helium/templates/head.template.html`:
    * each page's description, canonical URL, feed link, and Open Graph and
    * Twitter card tags for link previews. Edition pages are marked as
    * articles, dated from their heading, described by their articles, and
    * shown with their own image. Their `og:url` is the edition's permanent
    * URL, also on the home page, so platforms that cache previews by URL show
    * a new preview for each new edition.
    */
  private def pageMetaDirectives(editions: Map[Path, Edition]) =
    new DirectiveRegistry {
      val spanDirectives = Nil
      val blockDirectives = Nil
      val linkDirectives = Nil
      val templateDirectives = Seq(
        TemplateDirectives.create("scalanewsPageMeta") {
          TemplateDirectives.dsl.cursor.map { cursor =>
            val edition = editions.get(cursor.path)
            val url = SiteFiles.pageUrl(cursor.path)
            val shareUrl =
              edition.fold(url)(e => SiteFiles.pageUrl(e.permalink))
            val image = edition.fold(SiteFiles.socialImageUrl)(e =>
              SiteFiles.siteUrl + SiteFiles.imagePath(e).toString.stripPrefix("/")
            )
            val title = cursor.target.title
              .map(_.extractText)
              .getOrElse(SiteFiles.siteTitle)
            val description =
              edition.fold(SiteFiles.siteDescription)(SiteFiles.description)
            def meta(attr: String, name: String, content: String) =
              s"""<meta $attr="$name" content="${SiteFiles.escape(content)}"/>"""
            val tags = List(
              meta("name", "description", description),
              s"""<link rel="canonical" href="${SiteFiles.escape(url)}"/>""",
              s"""<link rel="alternate" type="application/atom+xml" title="${SiteFiles.siteTitle}" href="${SiteFiles.feedUrl}"/>""",
              meta("property", "og:site_name", SiteFiles.siteTitle),
              meta("property", "og:title", title),
              meta("property", "og:description", description),
              meta("property", "og:url", shareUrl),
              meta("property", "og:type", if (edition.isDefined) "article" else "website"),
              meta("property", "og:image", image),
              meta("property", "og:image:width", "1200"),
              meta("property", "og:image:height", "630"),
              meta("property", "og:image:alt", title),
              meta("name", "twitter:card", "summary_large_image")
            ) ++ edition.map(e =>
              meta("property", "article:published_time", e.date.toString)
            )
            TemplateString(tags.mkString("\n  "))
          }
        }
      )
    }

  /** "Share this edition" links under an edition's heading: each opens the
    * platform's own compose or submit page with the edition's title and
    * permanent URL filled in, so shares get that edition's link preview. Plain
    * links: no scripts or trackers. Mastodon has no single share URL (every
    * server differs), so it goes through toot.kytta.dev, which asks for the
    * reader's server.
    */
  private def shareLinks(edition: Edition): String = {
    def enc(value: String) =
      URLEncoder.encode(value, StandardCharsets.UTF_8).replace("+", "%20")
    val url = SiteFiles.pageUrl(edition.permalink)
    val title = edition.title
    val text = enc(s"$title $url")
    // In alphabetical order.
    val links = List(
      "Bluesky" -> s"https://bsky.app/intent/compose?text=$text",
      "Email" -> s"mailto:?subject=${enc(title)}&body=${enc(url)}",
      "Hacker News" -> s"https://news.ycombinator.com/submitlink?u=${enc(url)}&t=${enc(title)}",
      "LinkedIn" -> s"https://www.linkedin.com/sharing/share-offsite/?url=${enc(url)}",
      "Mastodon" -> s"https://toot.kytta.dev/?text=$text",
      "Reddit" -> s"https://www.reddit.com/submit?url=${enc(url)}&title=${enc(title)}",
      "X" -> s"https://x.com/intent/tweet?text=${enc(title)}&url=${enc(url)}"
    ).map { (name, href) =>
      val newTab =
        if (href.startsWith("mailto:")) ""
        else """ target="_blank" rel="noopener noreferrer""""
      s"""<a href="${SiteFiles.escape(href)}"$newTab>$name</a>"""
    }
    // The edition's own URL, to copy (right-click, "Copy link") or open: on
    // the home page the address bar only shows the site's.
    val permanentLink =
      s"""<a class="share-permalink" href="${SiteFiles.escape(url)}">Permanent link</a>"""
    s"""<p class="share-links"><span class="share-label">Share this edition:</span> ${(links :+ permanentLink)
        .mkString(""" <span class="share-sep">·</span> """)}</p>"""
  }

  def transformer(editions: List[Edition]): Resource[IO, TreeTransformer[IO]] = {
    val editionsByTitle = editions.map(e => e.title -> e).toMap
    Transformer
      .from(Markdown)
      .to(HTML)
      .using(Markdown.GitHubFlavor)
      // Newsletter pages embed HTML (the article cards); render it rather than escape it.
      .withRawContent
      .usingBlockRule(editionTitle)
      .using(
        pageMetaDirectives(
          editions.flatMap(e => List(e.path -> e, e.permalink -> e)).toMap
        )
      )
      .rendering {
        case (fmt, date @ Text(text, options))
            if options.styles("edition-date") && isoDate(text).isDefined =>
          fmt.textElement("time", date, "datetime" -> isoDate(text).get)
        // An edition's heading, followed by its share links.
        case (fmt, title: Title)
            if editionsByTitle.contains(title.extractText) =>
          fmt.element("h1", title) + "\n" +
            shareLinks(editionsByTitle(title.extractText))
      }
      .parallel[IO]
      .withTheme(helium)
      .build
  }
}
